In [24]:
import numpy as np
import pandas
import matplotlib.pyplot as plt
import scipy.fftpack
from scipy import signal
import scipy.interpolate

In [25]:
import h5py

In [26]:
ls

100_hotstuff_not_moving.bag     hotwire_100.bag         motor_hotwire_50.hdf5
2020-03-16-16-52-45.bag         hotwire_100.hdf5        motor_hotwire_tb.bag
2020-03-16-16-59-14.bag         hotwire_50.bag          motor_hotwire_tb.hdf5
2020-03-16-17-00-16.bag         hotwire_50.hdf5         new_100.bag
analyze_trisonica_sensor.ipynb  hotwire_tb.bag          new_100.hdf5
bag2hdf5.py                     hotwire_tb.hdf5         new_cal.bag
closed_hotwire.bag              motor_hotwire_100.bag   new_cal.hdf5
Heat_map_1.ipynb                motor_hotwire_100.hdf5  test.ipynb
Heat_map_hotwire_100.ipynb      motor_hotwire_50.bag

In [27]:
filename = 'motor_hotwire_100.hdf5'
df = pandas.read_hdf(filename)

ValueError: No dataset in HDF5 file.

In [110]:
def get_pandas_dataframe_from_uncooperative_hdf5(filename, key='first_key'):
    f = h5py.File(filename,'r')
    all_keys = list(f.keys())
    
    if key == 'first_key':
        print('Dataset contains these keys: ')
        print(all_keys)
        key = all_keys[0]
        print('Using only the first key: ', key)
        
    data = f[key][()]
    dic = {}
    for column_label in data.dtype.fields.keys():
        dic.setdefault(column_label, data[column_label])
    df = pandas.DataFrame(dic)
    return df

In [111]:
filename = 'motor_hotwire_100.hdf5'
df = get_pandas_dataframe_from_uncooperative_hdf5(filename)

Dataset contains these keys:
['motopub']
Using only the first key:  motopub

In [112]:
df

     data_0  data_1      t_secs    t_nsecs             t
0      1000     100  1584407227  946222899  1.584407e+09
1      2000     100  1584407263   92530524  1.584407e+09
2      3000     100  1584407298  234671574  1.584407e+09
3      4000     100  1584407333  355639621  1.584407e+09
4      5000     100  1584407368  496399078  1.584407e+09
..      ...     ...         ...        ...           ...
229    3290 -559200  1584415455  902828179  1.584415e+09
230    2290 -559200  1584415491   46701271  1.584415e+09
231    1290 -559200  1584415526  190101809  1.584416e+09
232     290 -559200  1584415561  339842153  1.584416e+09
233     190 -559200  1584415591  856269662  1.584416e+09

[234 rows x 5 columns]